name: Cross-compile native libraries
on: workflow_dispatch

env:
  MAVEN_CLI: -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  create-branch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "precompiled_branch=$(git branch --show-current)-precompiled-natives" >> $GITHUB_ENV
      - run: echo "rev=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Create branch for precompiled natives
        run: git checkout -b ${{ env.precompiled_branch }} && git push --force origin HEAD
    outputs:
      precompiled_branch: ${{ env.precompiled_branch }}
      base_rev: ${{ env.rev }}

  compile-natives:
    runs-on: ${{ matrix.os }}
    needs: create-branch
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            profile: 'm32'
            packages: 'cmake g++-multilib'
          - os: ubuntu-18.04
            profile: 'm64'
            packages: 'cmake g++'
          - os: ubuntu-18.04
            profile: 'mingw32'
            packages: 'cmake g++-mingw-w64-i686'
          - os: ubuntu-18.04
            profile: 'mingw64'
            packages: 'cmake g++-mingw-w64-x86-64'
          - os: ubuntu-18.04
            profile: 'armhf,armtrusty'
            packages: 'cmake g++-arm-linux-gnueabihf'
          - os: ubuntu-18.04
            profile: 'aarch64'
            packages: 'cmake g++-aarch64-linux-gnu'
          - os: ubuntu-18.04
            profile: 'ppc64'
            packages: 'cmake g++-powerpc64le-linux-gnu'
          - os: macos-10.15
            profile: 'osx'
            packages: 'cmake'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup APT packages
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: sudo apt-get install --yes ${{ matrix.packages }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prep Maven Repo
        run: mvn ${MAVEN_CLI} dependency:resolve-plugins dependency:resolve
      - name: Build with Maven
        run: mvn ${MAVEN_CLI} clean install -P ${{ matrix.profile }}
      - run: git config --global user.email "<>"
      - run: git config --global user.name "Automated build on Github"
      - run: git fetch && git checkout -t origin/${{ needs.create-branch.outputs.precompiled_branch }}
      - run: git add src/main/resources-precompiled/**
      - run: git commit --allow-empty -m "Precompiled natives (@${{ needs.create-branch.outputs.base_rev }}) for ${{ matrix.profile }}"
      - name: Push recompiled binary for ${{ matrix.profile }}
        run: 'while  git pull --rebase && ! git push; do sleep 5; done'
