name: Maven Central Relase
on: workflow_dispatch

env:
  MAVEN_CLI: -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  github-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prep Maven Repo
        run: mvn ${MAVEN_CLI} dependency:resolve-plugins dependency:resolve
      - name: Build fat jar with Maven
        run: mvn ${MAVEN_CLI} clean package -P package,jar-with-dependencies
      - name: Publish artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          title: "New Release"
          prerelease: true
          files: target/*.jar